### ISSUE TITLE
R2.3: Provide a few sentences on the history of Git

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#284]
Reviewer 2 comment

> R2.3. I would find it helpful to give a brief (1-2 sentence) history of Git (L85-89). Namely, that it was developed as an aid for software development within distributed groups of software engineers and was developed within an open-source framework so that it could be improved by the community. This provides more context as to why Github (as it extends Git) is a useful tool for collaboration “by design”.

Recommendations during the revision:

1. When performing changes addressing this comment, please recall this issue (using `#` followed by the number of this issue) in the pull request; and,
2. Clearly justify changes in the final comment of the pull request (to allow us to revise the manuscript in time).

**Comment by katherinehebert** [comment]
Thanks, @pedrohbraga, this edit addresses the reviewer's comment! I have added additional information about how far Git has come since its inception as a software development tool, from a paper I was saving.

I think these two edits address the comment, and this issue can be closed after merging the PR.
