### ISSUE TITLE
E1.5: Improve the discussion about the advantages of GitHub over other existing and less technically complicated tools

### ISSUE THREAD

**Issue by pedrohbraga** [SORTEE-Github-Hackathon/manuscript#291]
Editor's comment

> E1.5. Finally, DropBox, SharePoint, and OneDrive are file-sharing systems that include version control, are widely supported, especially in colleges and universities, and are much easier to use for those who might be uncomfortable learning a system such as GitHub. Other than the ability to clone and fork, why should one choose GitHub over, for example, DropBox or SharePoint? More should be made of this in text, as opposed to burying it in Table 1, which is referenced only once in text (line 232) and only in the context of other longterm archives (line 231). Indeed, I suggest a somewhat expanded section of the ms. dedicated to a detailed exploration of the comparisons made in this Table. Otherwise, the ms. comes across as more proselytizing and less analytical/convincing.

Recommendations during the revision:

1. When performing changes addressing this comment, please recall this issue (using `#` followed by the number of this issue) in the pull request; and,
2. Clearly justify changes in the final comment of the pull request (to allow us to revise the manuscript in time).

**Comment by robcrystalornelas** [comment]
I opened PR #301 to address comments in this issue.

### General ways that I address comments
Rather than create a new section as the editor suggested, I opted to identnify specific points in the manuscript where we could directly call out where GitHub as a platform enables greater or different types of collaboration and open science than platforms like dropbox or google. Due to these edits (below) we now more often refer to table 1, and earlier in the manuscript as well.

### Specific updates

updates throughout the text to emphasize how GitHub is different from other cloud-based platforms for collaboration.

1st paragraph of intro I made text more concise throughout and also added new sentence:
>Of all these tools, GitHub is uniquely positioned ([Table 1](#tbl:compare)) to benefit scientists because the platform is designed to enable collaboration on computer code--a fundamental component of modern research.

2nd paragraph addition:
>Additionally, unlike sharing documents and code via DropBox or Google Drive links, GitHub defaults to public sharing of code and documents and has features like Issues and Discussions (see [Box 1](#definitions)) that can immediately and directly contribute to more open science and knowledge sharing.

Under storing a research compendium:
>While some EEB researchers may prefer to store their code in Google Drive or DropBox, the process of sharing code through these services becomes cumbersome when collaborators have to download and re-upload edited code.
>On GitHub, code is by default public, and the process of forking and submitting pull requests (see [Box 1](#definitions)) ensures a code owner has full control over code and documents in a repository.


First paragraph of discussion
>While tools like the Google Suite and DropBox enable rapid sharing and collaboration of some research documents, GitHub brings together features that directly address open science such as tools for soliciting public discussions on code and findings, tracking multiple rounds of edits to files in a sensible way for easy review, and managing complex research projects with many collaborators and goals.


In discussion, under "why aren't more EEB researchers using github"
> And with institutional availability of software licenses for tools like the Google Suite or Microsoft Office, researchers may be hesitant to spend valuable time learning another tool.
